name: Fetch Strava Activities

# Give the checkout/Git steps permission to write back to the repo
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true    # ensures GITHUB_TOKEN is available
          fetch-depth: 0

      - name: Fetch activities from Strava
        env:
          STRAVA_TOKEN: ${{ secrets.STRAVA_TOKEN }}
        run: |
          set -euxo pipefail

          echo "→ Fetching Strava activities…"
          HTTP_CODE=$(curl -s -w "%{http_code}" -G \
            -H "Authorization: Bearer $STRAVA_TOKEN" \
            "https://www.strava.com/api/v3/athlete/activities" \
            -o activities.json)

          echo "→ HTTP response code: $HTTP_CODE"
          if [ "$HTTP_CODE" -ne 200 ]; then
            echo "⚠️ Strava API returned non-200 status. Dumping response:"
            cat activities.json
            exit 1
          fi

          COUNT=$(jq length activities.json)
          echo "→ Retrieved $COUNT activities"
          echo "→ Showing first 3 entries:"
          jq '.[0:3]' activities.json

      - name: Commit updated activities.json if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          if git diff --quiet activities.json; then
            echo "→ No changes in activities.json; skipping commit."
          else
            git add activities.json
            git commit -m "chore: update Strava activities"
            git push
          fi
