name: Fetch Strava Activities

# Give the checkout/Git steps permission to write back to the repo
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'



jobs:
  update:
    runs-on: ubuntu-latest
    steps:
  - uses: actions/checkout@v4
    with:
      persist-credentials: true    # ← makes sure GITHUB_TOKEN is cached
      fetch-depth: 0
  # …

      - name: Fetch activities from Strava
        env:
          STRAVA_TOKEN: ${{ secrets.STRAVA_TOKEN }}
        run: |
          curl -s -G \
            -H "Authorization: Bearer $STRAVA_TOKEN" \
            "https://www.strava.com/api/v3/athlete/activities" \
            > activities.json

      - name: Commit updated activities.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add activities.json
          git commit -m "chore: update Strava activities" || echo "No changes to commit"
          git push
