# .github/workflows/fetch-strava.yml
name: Fetch Strava Activities

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Refresh Strava token
        env:
          STRAVA_CLIENT_ID:     ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          echo "→ Exchanging refresh token for new access token…"
          curl -s -X POST https://www.strava.com/oauth/token \
            -d client_id=$STRAVA_CLIENT_ID \
            -d client_secret=$STRAVA_CLIENT_SECRET \
            -d grant_type=refresh_token \
            -d refresh_token=$STRAVA_REFRESH_TOKEN \
            > token.json
          echo "→ Token refreshed."

      - name: Fetch activities from Strava
        run: |
          echo "→ Fetching Strava activities…"
          ACCESS_TOKEN=$(jq -r .access_token token.json)
          curl -s -G \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            "https://www.strava.com/api/v3/athlete/activities" \
            > activities.json
          echo "→ Activities downloaded."

      - name: Commit and push new activities
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add activities.json
          git commit -m "Update activities.json" || echo "No changes to commit"
          git push
